-- File: app/countries.lua
-- Desc: auto generated list of countries, iso and iso => country

local countries = {
    --list of countries
    list = {
        { name = 'Afghanistan', iso = 'AFG' },
        { name = 'Aland Islands', iso = 'ALA' },
        { name = 'Albania', iso = 'ALB' },
        { name = 'Algeria', iso = 'DZA' },
        { name = 'American Samoa', iso = 'ASM' },
        { name = 'Andorra', iso = 'AND' },
        { name = 'Angola', iso = 'AGO' },
        { name = 'Anguilla', iso = 'AIA' },
        { name = 'Antarctica', iso = 'ATA' },
        { name = 'Antigua and Barbuda', iso = 'ATG' },
        { name = 'Argentina', iso = 'ARG' },
        { name = 'Armenia', iso = 'ARM' },
        { name = 'Aruba', iso = 'ABW' },
        { name = 'Australia', iso = 'AUS' },
        { name = 'Austria', iso = 'AUT' },
        { name = 'Azerbaijan', iso = 'AZE' },
        { name = 'Bahamas', iso = 'BHS' },
        { name = 'Bahrain', iso = 'BHR' },
        { name = 'Bangladesh', iso = 'BGD' },
        { name = 'Barbados', iso = 'BRB' },
        { name = 'Belarus', iso = 'BLR' },
        { name = 'Belgium', iso = 'BEL' },
        { name = 'Belize', iso = 'BLZ' },
        { name = 'Benin', iso = 'BEN' },
        { name = 'Bermuda', iso = 'BMU' },
        { name = 'Bhutan', iso = 'BTN' },
        { name = 'Bolivia', iso = 'BOL' },
        { name = 'Bonaire, Sint Eustatius and Saba', iso = 'BES' },
        { name = 'Bosnia and Herzegovina', iso = 'BIH' },
        { name = 'Botswana', iso = 'BWA' },
        { name = 'Bouvet Island', iso = 'BVT' },
        { name = 'Brazil', iso = 'BRA' },
        { name = 'British Indian Ocean Territory', iso = 'IOT' },
        { name = 'Brunei', iso = 'BRN' },
        { name = 'Bulgaria', iso = 'BGR' },
        { name = 'Burkina Faso', iso = 'BFA' },
        { name = 'Burundi', iso = 'BDI' },
        { name = 'Cambodia', iso = 'KHM' },
        { name = 'Cameroon', iso = 'CMR' },
        { name = 'Canada', iso = 'CAN' },
        { name = 'Cape Verde', iso = 'CPV' },
        { name = 'Cayman Islands', iso = 'CYM' },
        { name = 'Central African Republic', iso = 'CAF' },
        { name = 'Chad', iso = 'TCD' },
        { name = 'Chile', iso = 'CHL' },
        { name = 'China', iso = 'CHN' },
        { name = 'Christmas Island', iso = 'CXR' },
        { name = 'Cocos (Keeling) Islands', iso = 'CCK' },
        { name = 'Colombia', iso = 'COL' },
        { name = 'Comoros', iso = 'COM' },
        { name = 'Congo', iso = 'COG' },
        { name = 'Cook Islands', iso = 'COK' },
        { name = 'Costa Rica', iso = 'CRI' },
        { name = 'Cote d\'ivoire (Ivory Coast)', iso = 'CIV' },
        { name = 'Croatia', iso = 'HRV' },
        { name = 'Cuba', iso = 'CUB' },
        { name = 'Curacao', iso = 'CUW' },
        { name = 'Cyprus', iso = 'CYP' },
        { name = 'Czech Republic', iso = 'CZE' },
        { name = 'Democratic Republic of the Congo', iso = 'COD' },
        { name = 'Denmark', iso = 'DNK' },
        { name = 'Djibouti', iso = 'DJI' },
        { name = 'Dominica', iso = 'DMA' },
        { name = 'Dominican Republic', iso = 'DOM' },
        { name = 'Ecuador', iso = 'ECU' },
        { name = 'Egypt', iso = 'EGY' },
        { name = 'El Salvador', iso = 'SLV' },
        { name = 'Equatorial Guinea', iso = 'GNQ' },
        { name = 'Eritrea', iso = 'ERI' },
        { name = 'Estonia', iso = 'EST' },
        { name = 'Ethiopia', iso = 'ETH' },
        { name = 'Falkland Islands (Malvinas)', iso = 'FLK' },
        { name = 'Faroe Islands', iso = 'FRO' },
        { name = 'Fiji', iso = 'FJI' },
        { name = 'Finland', iso = 'FIN' },
        { name = 'France', iso = 'FRA' },
        { name = 'French Guiana', iso = 'GUF' },
        { name = 'French Polynesia', iso = 'PYF' },
        { name = 'French Southern Territories', iso = 'ATF' },
        { name = 'Gabon', iso = 'GAB' },
        { name = 'Gambia', iso = 'GMB' },
        { name = 'Georgia', iso = 'GEO' },
        { name = 'Germany', iso = 'DEU' },
        { name = 'Ghana', iso = 'GHA' },
        { name = 'Gibraltar', iso = 'GIB' },
        { name = 'Greece', iso = 'GRC' },
        { name = 'Greenland', iso = 'GRL' },
        { name = 'Grenada', iso = 'GRD' },
        { name = 'Guadaloupe', iso = 'GLP' },
        { name = 'Guam', iso = 'GUM' },
        { name = 'Guatemala', iso = 'GTM' },
        { name = 'Guernsey', iso = 'GGY' },
        { name = 'Guinea', iso = 'GIN' },
        { name = 'Guinea-Bissau', iso = 'GNB' },
        { name = 'Guyana', iso = 'GUY' },
        { name = 'Haiti', iso = 'HTI' },
        { name = 'Heard Island and McDonald Islands', iso = 'HMD' },
        { name = 'Honduras', iso = 'HND' },
        { name = 'Hong Kong', iso = 'HKG' },
        { name = 'Hungary', iso = 'HUN' },
        { name = 'Iceland', iso = 'ISL' },
        { name = 'India', iso = 'IND' },
        { name = 'Indonesia', iso = 'IDN' },
        { name = 'Iran', iso = 'IRN' },
        { name = 'Iraq', iso = 'IRQ' },
        { name = 'Ireland', iso = 'IRL' },
        { name = 'Isle of Man', iso = 'IMN' },
        { name = 'Israel', iso = 'ISR' },
        { name = 'Italy', iso = 'ITA' },
        { name = 'Jamaica', iso = 'JAM' },
        { name = 'Japan', iso = 'JPN' },
        { name = 'Jersey', iso = 'JEY' },
        { name = 'Jordan', iso = 'JOR' },
        { name = 'Kazakhstan', iso = 'KAZ' },
        { name = 'Kenya', iso = 'KEN' },
        { name = 'Kiribati', iso = 'KIR' },
        { name = 'Kosovo', iso = '---' },
        { name = 'Kuwait', iso = 'KWT' },
        { name = 'Kyrgyzstan', iso = 'KGZ' },
        { name = 'Laos', iso = 'LAO' },
        { name = 'Latvia', iso = 'LVA' },
        { name = 'Lebanon', iso = 'LBN' },
        { name = 'Lesotho', iso = 'LSO' },
        { name = 'Liberia', iso = 'LBR' },
        { name = 'Libya', iso = 'LBY' },
        { name = 'Liechtenstein', iso = 'LIE' },
        { name = 'Lithuania', iso = 'LTU' },
        { name = 'Luxembourg', iso = 'LUX' },
        { name = 'Macao', iso = 'MAC' },
        { name = 'Macedonia', iso = 'MKD' },
        { name = 'Madagascar', iso = 'MDG' },
        { name = 'Malawi', iso = 'MWI' },
        { name = 'Malaysia', iso = 'MYS' },
        { name = 'Maldives', iso = 'MDV' },
        { name = 'Mali', iso = 'MLI' },
        { name = 'Malta', iso = 'MLT' },
        { name = 'Marshall Islands', iso = 'MHL' },
        { name = 'Martinique', iso = 'MTQ' },
        { name = 'Mauritania', iso = 'MRT' },
        { name = 'Mauritius', iso = 'MUS' },
        { name = 'Mayotte', iso = 'MYT' },
        { name = 'Mexico', iso = 'MEX' },
        { name = 'Micronesia', iso = 'FSM' },
        { name = 'Moldava', iso = 'MDA' },
        { name = 'Monaco', iso = 'MCO' },
        { name = 'Mongolia', iso = 'MNG' },
        { name = 'Montenegro', iso = 'MNE' },
        { name = 'Montserrat', iso = 'MSR' },
        { name = 'Morocco', iso = 'MAR' },
        { name = 'Mozambique', iso = 'MOZ' },
        { name = 'Myanmar (Burma)', iso = 'MMR' },
        { name = 'Namibia', iso = 'NAM' },
        { name = 'Nauru', iso = 'NRU' },
        { name = 'Nepal', iso = 'NPL' },
        { name = 'Netherlands', iso = 'NLD' },
        { name = 'New Caledonia', iso = 'NCL' },
        { name = 'New Zealand', iso = 'NZL' },
        { name = 'Nicaragua', iso = 'NIC' },
        { name = 'Niger', iso = 'NER' },
        { name = 'Nigeria', iso = 'NGA' },
        { name = 'Niue', iso = 'NIU' },
        { name = 'Norfolk Island', iso = 'NFK' },
        { name = 'North Korea', iso = 'PRK' },
        { name = 'Northern Mariana Islands', iso = 'MNP' },
        { name = 'Norway', iso = 'NOR' },
        { name = 'Oman', iso = 'OMN' },
        { name = 'Pakistan', iso = 'PAK' },
        { name = 'Palau', iso = 'PLW' },
        { name = 'Palestine', iso = 'PSE' },
        { name = 'Panama', iso = 'PAN' },
        { name = 'Papua New Guinea', iso = 'PNG' },
        { name = 'Paraguay', iso = 'PRY' },
        { name = 'Peru', iso = 'PER' },
        { name = 'Phillipines', iso = 'PHL' },
        { name = 'Pitcairn', iso = 'PCN' },
        { name = 'Poland', iso = 'POL' },
        { name = 'Portugal', iso = 'PRT' },
        { name = 'Puerto Rico', iso = 'PRI' },
        { name = 'Qatar', iso = 'QAT' },
        { name = 'Reunion', iso = 'REU' },
        { name = 'Romania', iso = 'ROU' },
        { name = 'Russia', iso = 'RUS' },
        { name = 'Rwanda', iso = 'RWA' },
        { name = 'Saint Barthelemy', iso = 'BLM' },
        { name = 'Saint Helena', iso = 'SHN' },
        { name = 'Saint Kitts and Nevis', iso = 'KNA' },
        { name = 'Saint Lucia', iso = 'LCA' },
        { name = 'Saint Martin', iso = 'MAF' },
        { name = 'Saint Pierre and Miquelon', iso = 'SPM' },
        { name = 'Saint Vincent and the Grenadines', iso = 'VCT' },
        { name = 'Samoa', iso = 'WSM' },
        { name = 'San Marino', iso = 'SMR' },
        { name = 'Sao Tome and Principe', iso = 'STP' },
        { name = 'Saudi Arabia', iso = 'SAU' },
        { name = 'Senegal', iso = 'SEN' },
        { name = 'Serbia', iso = 'SRB' },
        { name = 'Seychelles', iso = 'SYC' },
        { name = 'Sierra Leone', iso = 'SLE' },
        { name = 'Singapore', iso = 'SGP' },
        { name = 'Sint Maarten', iso = 'SXM' },
        { name = 'Slovakia', iso = 'SVK' },
        { name = 'Slovenia', iso = 'SVN' },
        { name = 'Solomon Islands', iso = 'SLB' },
        { name = 'Somalia', iso = 'SOM' },
        { name = 'South Africa', iso = 'ZAF' },
        { name = 'South Georgia and the South Sandwich Islands', iso = 'SGS' },
        { name = 'South Korea', iso = 'KOR' },
        { name = 'South Sudan', iso = 'SSD' },
        { name = 'Spain', iso = 'ESP' },
        { name = 'Sri Lanka', iso = 'LKA' },
        { name = 'Sudan', iso = 'SDN' },
        { name = 'Suriname', iso = 'SUR' },
        { name = 'Svalbard and Jan Mayen', iso = 'SJM' },
        { name = 'Swaziland', iso = 'SWZ' },
        { name = 'Sweden', iso = 'SWE' },
        { name = 'Switzerland', iso = 'CHE' },
        { name = 'Syria', iso = 'SYR' },
        { name = 'Taiwan', iso = 'TWN' },
        { name = 'Tajikistan', iso = 'TJK' },
        { name = 'Tanzania', iso = 'TZA' },
        { name = 'Thailand', iso = 'THA' },
        { name = 'Timor-Leste (East Timor)', iso = 'TLS' },
        { name = 'Togo', iso = 'TGO' },
        { name = 'Tokelau', iso = 'TKL' },
        { name = 'Tonga', iso = 'TON' },
        { name = 'Trinidad and Tobago', iso = 'TTO' },
        { name = 'Tunisia', iso = 'TUN' },
        { name = 'Turkey', iso = 'TUR' },
        { name = 'Turkmenistan', iso = 'TKM' },
        { name = 'Turks and Caicos Islands', iso = 'TCA' },
        { name = 'Tuvalu', iso = 'TUV' },
        { name = 'Uganda', iso = 'UGA' },
        { name = 'Ukraine', iso = 'UKR' },
        { name = 'United Arab Emirates', iso = 'ARE' },
        { name = 'United Kingdom', iso = 'GBR' },
        { name = 'United States', iso = 'USA' },
        { name = 'United States Minor Outlying Islands', iso = 'UMI' },
        { name = 'Uruguay', iso = 'URY' },
        { name = 'Uzbekistan', iso = 'UZB' },
        { name = 'Vanuatu', iso = 'VUT' },
        { name = 'Vatican City', iso = 'VAT' },
        { name = 'Venezuela', iso = 'VEN' },
        { name = 'Vietnam', iso = 'VNM' },
        { name = 'Virgin Islands, British', iso = 'VGB' },
        { name = 'Virgin Islands, US', iso = 'VIR' },
        { name = 'Wallis and Futuna', iso = 'WLF' },
        { name = 'Western Sahara', iso = 'ESH' },
        { name = 'Yemen', iso = 'YEM' },
        { name = 'Zambia', iso = 'ZMB' },
        { name = 'Zimbabwe', iso = 'ZWE' }
    },
    --iso => country name
    iso = {
        THA = 'Thailand',
        SLV = 'El Salvador',
        TCD = 'Chad',
        MLT = 'Malta',
        ECU = 'Ecuador',
        GTM = 'Guatemala',
        MNG = 'Mongolia',
        USA = 'United States',
        SOM = 'Somalia',
        BES = 'Bonaire, Sint Eustatius and Saba',
        DZA = 'Algeria',
        GIN = 'Guinea',
        PRI = 'Puerto Rico',
        MSR = 'Montserrat',
        ZWE = 'Zimbabwe',
        FIN = 'Finland',
        ZMB = 'Zambia',
        BTN = 'Bhutan',
        ITA = 'Italy',
        BDI = 'Burundi',
        TON = 'Tonga',
        PNG = 'Papua New Guinea',
        NGA = 'Nigeria',
        KWT = 'Kuwait',
        ARM = 'Armenia',
        YEM = 'Yemen',
        NER = 'Niger',
        CUW = 'Curacao',
        LBN = 'Lebanon',
        NFK = 'Norfolk Island',
        SJM = 'Svalbard and Jan Mayen',
        WLF = 'Wallis and Futuna',
        KNA = 'Saint Kitts and Nevis',
        TKM = 'Turkmenistan',
        SAU = 'Saudi Arabia',
        VGB = 'Virgin Islands, British',
        VNM = 'Vietnam',
        CHE = 'Switzerland',
        VEN = 'Venezuela',
        AUT = 'Austria',
        ISR = 'Israel',
        MNP = 'Northern Mariana Islands',
        ALB = 'Albania',
        CXR = 'Christmas Island',
        IND = 'India',
        CUB = 'Cuba',
        VUT = 'Vanuatu',
        UZB = 'Uzbekistan',
        URY = 'Uruguay',
        UMI = 'United States Minor Outlying Islands',
        GBR = 'United Kingdom',
        ARE = 'United Arab Emirates',
        TUR = 'Turkey',
        MDG = 'Madagascar',
        BEN = 'Benin',
        SHN = 'Saint Helena',
        UGA = 'Uganda',
        KEN = 'Kenya',
        TUV = 'Tuvalu',
        TCA = 'Turks and Caicos Islands',
        PSE = 'Palestine',
        BGR = 'Bulgaria',
        SGS = 'South Georgia and the South Sandwich Islands',
        VIR = 'Virgin Islands, US',
        ALA = 'Aland Islands',
        PAK = 'Pakistan',
        AZE = 'Azerbaijan',
        GEO = 'Georgia',
        JPN = 'Japan',
        GNQ = 'Equatorial Guinea',
        TUN = 'Tunisia',
        TTO = 'Trinidad and Tobago',
        GLP = 'Guadaloupe',
        TKL = 'Tokelau',
        TGO = 'Togo',
        TLS = 'Timor-Leste (East Timor)',
        KAZ = 'Kazakhstan',
        HTI = 'Haiti',
        GNB = 'Guinea-Bissau',
        BLR = 'Belarus',
        TZA = 'Tanzania',
        TJK = 'Tajikistan',
        IRL = 'Ireland',
        GAB = 'Gabon',
        DJI = 'Djibouti',
        RUS = 'Russia',
        BEL = 'Belgium',
        COK = 'Cook Islands',
        CCK = 'Cocos (Keeling) Islands',
        AUS = 'Australia',
        SWE = 'Sweden',
        SSD = 'South Sudan',
        FRA = 'France',
        MUS = 'Mauritius',
        SWZ = 'Swaziland',
        SPM = 'Saint Pierre and Miquelon',
        MOZ = 'Mozambique',
        ESH = 'Western Sahara',
        SUR = 'Suriname',
        AFG = 'Afghanistan',
        LKA = 'Sri Lanka',
        COD = 'Democratic Republic of the Congo',
        KIR = 'Kiribati',
        BWA = 'Botswana',
        ESP = 'Spain',
        EST = 'Estonia',
        JAM = 'Jamaica',
        BRN = 'Brunei',
        NPL = 'Nepal',
        SLB = 'Solomon Islands',
        SVN = 'Slovenia',
        AGO = 'Angola',
        HUN = 'Hungary',
        SVK = 'Slovakia',
        IRN = 'Iran',
        SXM = 'Sint Maarten',
        NCL = 'New Caledonia',
        SGP = 'Singapore',
        HMD = 'Heard Island and McDonald Islands',
        SLE = 'Sierra Leone',
        ERI = 'Eritrea',
        BFA = 'Burkina Faso',
        AIA = 'Anguilla',
        CAN = 'Canada',
        LAO = 'Laos',
        SRB = 'Serbia',
        IRQ = 'Iraq',
        IOT = 'British Indian Ocean Territory',
        SEN = 'Senegal',
        STP = 'Sao Tome and Principe',
        SMR = 'San Marino',
        LBR = 'Liberia',
        ROU = 'Romania',
        WSM = 'Samoa',
        VCT = 'Saint Vincent and the Grenadines',
        MAF = 'Saint Martin',
        MDV = 'Maldives',
        GGY = 'Guernsey',
        UKR = 'Ukraine',
        EGY = 'Egypt',
        BLM = 'Saint Barthelemy',
        BMU = 'Bermuda',
        MKD = 'Macedonia',
        CZE = 'Czech Republic',
        RWA = 'Rwanda',
        SYR = 'Syria',
        REU = 'Reunion',
        ATF = 'French Southern Territories',
        QAT = 'Qatar',
        NAM = 'Namibia',
        CIV = 'Cote d\'ivoire (Ivory Coast)',
        POL = 'Poland',
        FLK = 'Falkland Islands (Malvinas)',
        MDA = 'Moldava',
        BVT = 'Bouvet Island',
        PCN = 'Pitcairn',
        KHM = 'Cambodia',
        PHL = 'Phillipines',
        BLZ = 'Belize',
        SYC = 'Seychelles',
        GMB = 'Gambia',
        PAN = 'Panama',
        CMR = 'Cameroon',
        CYM = 'Cayman Islands',
        ISL = 'Iceland',
        GIB = 'Gibraltar',
        MCO = 'Monaco',
        LTU = 'Lithuania',
        CAF = 'Central African Republic',
        BRB = 'Barbados',
        PRK = 'North Korea',
        NRU = 'Nauru',
        JEY = 'Jersey',
        NIC = 'Nicaragua',
        NZL = 'New Zealand',
        ABW = 'Aruba',
        MHL = 'Marshall Islands',
        NLD = 'Netherlands',
        LIE = 'Liechtenstein',
        MLI = 'Mali',
        MMR = 'Myanmar (Burma)',
        NIU = 'Niue',
        GUM = 'Guam',
        PRT = 'Portugal',
        MAR = 'Morocco',
        ETH = 'Ethiopia',
        CHN = 'China',
        BGD = 'Bangladesh',
        CHL = 'Chile',
        CYP = 'Cyprus',
        TWN = 'Taiwan',
        MEX = 'Mexico',
        CPV = 'Cape Verde',
        MTQ = 'Martinique',
        LCA = 'Saint Lucia',
        ARG = 'Argentina',
        MYS = 'Malaysia',
        HKG = 'Hong Kong',
        MWI = 'Malawi',
        KGZ = 'Kyrgyzstan',
        MAC = 'Macao',
        ATA = 'Antarctica',
        PLW = 'Palau',
        GRD = 'Grenada',
        COM = 'Comoros',
        FSM = 'Micronesia',
        ASM = 'American Samoa',
        DMA = 'Dominica',
        AND = 'Andorra',
        SDN = 'Sudan',
        LBY = 'Libya',
        COG = 'Congo',
        MRT = 'Mauritania',
        MNE = 'Montenegro',
        GRC = 'Greece',
        GRL = 'Greenland',
        IMN = 'Isle of Man',
        BHR = 'Bahrain',
        NOR = 'Norway',
        HRV = 'Croatia',
        BIH = 'Bosnia and Herzegovina',
        CRI = 'Costa Rica',
        JOR = 'Jordan',
        FJI = 'Fiji',
        BRA = 'Brazil',
        KOR = 'South Korea',
        DNK = 'Denmark',
        PER = 'Peru',
        COL = 'Colombia',
        BOL = 'Bolivia',
        FRO = 'Faroe Islands',
        BHS = 'Bahamas',
        GHA = 'Ghana',
        PRY = 'Paraguay',
        HND = 'Honduras',
        LUX = 'Luxembourg',
        PYF = 'French Polynesia',
        DEU = 'Germany',
        OMN = 'Oman',
        ATG = 'Antigua and Barbuda',
        GUF = 'French Guiana',
        DOM = 'Dominican Republic',
        LVA = 'Latvia',
        LSO = 'Lesotho',
        VAT = 'Vatican City',
        IDN = 'Indonesia',
        GUY = 'Guyana',
        MYT = 'Mayotte',
        ZAF = 'South Africa'
    }
}

return countries