Vagrant.configure('2') do |config|
    # All get some cpu + ram
    config.vm.provider 'virtualbox' do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end

    # Dev (Centos 6.5)
    config.vm.define 'dev' do |dev|
        # Make dev beefy
        dev.vm.provider 'virtualbox' do |vb|
            vb.memory = 2048
            vb.cpus = 4
        end
        dev.vm.box = 'centos64'
        dev.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box'
        dev.vm.network :private_network, ip: '13.13.13.13'
        dev.vm.synced_folder '../', '/opt/oxypanel/src'
        dev.vm.provision 'shell', path: './install.sh', args: ['debug']
    end

    # Debian 7
    config.vm.define 'debian' do |debian|
        debian.vm.box = 'debian64'
        debian.vm.box_url = 'https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box'
        debian.vm.network :private_network, ip: '15.15.15.15'
        debian.vm.provision 'shell', path: './install.sh', args: ['debug']
    end

    # Ubuntu 13.10
    config.vm.define 'ubuntu' do |ubuntu|
        ubuntu.vm.box = 'ubuntu64'
        ubuntu.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'
        ubuntu.vm.network :private_network, ip: '16.16.16.16'
        ubuntu.vm.provision 'shell', path: './install.sh'
    end

    # Centos 6.5
    config.vm.define 'centos' do |centos|
        centos.vm.box = 'centos64'
        centos.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box'
        centos.vm.network :private_network, ip: '17.17.17.17'
        centos.vm.provision 'shell', path: './install.sh'
    end
end