Vagrant.configure( '2' ) do |config|
    # All get some ram
    config.vm.provider :virtualbox do |vb|
        vb.customize ['modifyvm', :id, '--memory', '512']
    end

    # All run install
    config.vm.provision 'shell', path: './install.sh'

    # Dev
    config.vm.define 'dev' do |dev|
        dev.vm.box = 'debian64'
        dev.vm.box_url = 'https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box'
        dev.vm.network :private_network, ip: '13.13.13.13'
        dev.vm.synced_folder '../', '/opt/oxypanel/src'
    end

    # Debian 7
    config.vm.define 'debian' do |debian|
        debian.vm.box = 'debian64'
        debian.vm.box_url = 'https://dl.dropboxusercontent.com/s/xymcvez85i29lym/vagrant-debian-wheezy64.box'
        debian.vm.network :private_network, ip: '15.15.15.15'
    end

    # Ubuntu 13.10
    config.vm.define 'ubuntu' do |ubuntu|
        ubuntu.vm.box = 'ubuntu64'
        ubuntu.vm.box_url = 'http://cloud-images.ubuntu.com/vagrant/saucy/current/saucy-server-cloudimg-amd64-vagrant-disk1.box'
        ubuntu.vm.network :private_network, ip: '16.16.16.16'
    end

    # Centos 6.5
    config.vm.define 'centos' do |centos|
        centos.vm.box = 'centos64'
        centos.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box'
        centos.vm.network :private_network, ip: '17.17.17.17'
    end
end